name: all_widgets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.0
  widget_with_codeview: ^3.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - lib/presentation/widgets/aboutdialog/
    - lib/presentation/widgets/aboutlisttile/
    - lib/presentation/widgets/absorbpointer/
    - lib/presentation/widgets/alertdialog/
    - lib/presentation/widgets/aling/
    - lib/presentation/widgets/animatedalign/
    - lib/presentation/widgets/animatedbuilder/
    - lib/presentation/widgets/animatedcontainer/
    - lib/presentation/widgets/animatedcrossfade/
    - lib/presentation/widgets/animateddefaulttextstyle/
    - lib/presentation/widgets/animatedicon/
    - lib/presentation/widgets/animatedlist/
    - lib/presentation/widgets/animatedmodalbarrier/
    - lib/presentation/widgets/animatedopacity/
    - lib/presentation/widgets/animatedpadding/
    - lib/presentation/widgets/animatedphysicalmodel/
    - lib/presentation/widgets/animatedpositioned/
    - lib/presentation/widgets/animatedrotation/
    - lib/presentation/widgets/animatedsize/

