name: all_widgets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.0
  isar:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  path_provider: ^2.1.5
  riverpod: ^2.6.1
  widget_with_codeview: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: 3.1.8

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icon/
    - lib/presentation/widgets/aboutdialog/
    - lib/presentation/widgets/aboutlisttile/
    - lib/presentation/widgets/absorbpointer/
    - lib/presentation/widgets/alertdialog/
    - lib/presentation/widgets/aling/
    - lib/presentation/widgets/animatedalign/
    - lib/presentation/widgets/animatedbuilder/
    - lib/presentation/widgets/animatedcontainer/
    - lib/presentation/widgets/animatedcrossfade/
    - lib/presentation/widgets/animateddefaulttextstyle/
    - lib/presentation/widgets/animatedicon/
    - lib/presentation/widgets/animatedlist/
    - lib/presentation/widgets/animatedmodalbarrier/
    - lib/presentation/widgets/animatedopacity/
    - lib/presentation/widgets/animatedpadding/
    - lib/presentation/widgets/animatedphysicalmodel/
    - lib/presentation/widgets/animatedpositioned/
    - lib/presentation/widgets/animatedrotation/
    - lib/presentation/widgets/animatedsize/
    - lib/presentation/widgets/animatedswitcher/
    - lib/presentation/widgets/appbar/
    - lib/presentation/widgets/aspectratio/
    - lib/presentation/widgets/autocomplete/
    - lib/presentation/widgets/backdropfilter/
    - lib/presentation/widgets/banner/
    - lib/presentation/widgets/baseline/
    - lib/presentation/widgets/blocksemantics/
    - lib/presentation/widgets/bottomnavigationbar/
    - lib/presentation/widgets/bottomsheet/
    - lib/presentation/widgets/builder/
    - lib/presentation/widgets/card/
    - lib/presentation/widgets/center/
    - lib/presentation/widgets/checkbox/
    - lib/presentation/widgets/checkboxlisttile/
    - lib/presentation/widgets/chip/
    - lib/presentation/widgets/choicechip/
    - lib/presentation/widgets/circleavatar/
    - lib/presentation/widgets/circularprogressindicator/
    - lib/presentation/widgets/clipoval/
    - lib/presentation/widgets/clippath/
    - lib/presentation/widgets/cliprect/
    - lib/presentation/widgets/cliprrect/
    - lib/presentation/widgets/closebutton/
    - lib/presentation/widgets/coloredbox/
    - lib/presentation/widgets/colorfiltered/
    - lib/presentation/widgets/constrainedbox/
    - lib/presentation/widgets/container/
    - lib/presentation/widgets/column/
    - lib/presentation/widgets/cupertinoactionsheetaction/
    - lib/presentation/widgets/cupertinoapp/
    - lib/presentation/widgets/cupertinoactivityindicator/
    - lib/presentation/widgets/cupertinoalertdialog/
    - lib/presentation/widgets/cupertinobutton/
    - lib/presentation/widgets/cupertinocontextmenu/
    - lib/presentation/widgets/cupertinodatepicker/
    - lib/presentation/widgets/cupertinopageroute/
    - lib/presentation/widgets/cupertinopagescaffold/
    - lib/presentation/widgets/cupertinopicker/
    - lib/presentation/widgets/cupertinopopupsurface/
    - lib/presentation/widgets/cupertinoscrollbar/
    - lib/presentation/widgets/cupertinosearchtextfield/
    - lib/presentation/widgets/cupertinosegmentedcontrol/
    - lib/presentation/widgets/cupertinoslider/
    - lib/presentation/widgets/cupertinoslidingsegmentedcontrol/
    - lib/presentation/widgets/cupertinoswitch/
    - lib/presentation/widgets/cupertinotabscaffold/
    - lib/presentation/widgets/cupertinotextfield/
    - lib/presentation/widgets/custompaint/
    - lib/presentation/widgets/customscrollview/
    - lib/presentation/widgets/datatable/
    - lib/presentation/widgets/datepicker/
    - lib/presentation/widgets/daterangepicker/
    - lib/presentation/widgets/decoratedbox/
    - lib/presentation/widgets/decoratedboxtransition/
    - lib/presentation/widgets/defaulttextstyle/
    - lib/presentation/widgets/dismissible/
    - lib/presentation/widgets/divider/
    - lib/presentation/widgets/draggable/
    - lib/presentation/widgets/draggablescrollable/
    - lib/presentation/widgets/dragtarget/
    - lib/presentation/widgets/drawer/
    - lib/presentation/widgets/drawerheader/
    - lib/presentation/widgets/elevatedbutton/
    - lib/presentation/widgets/expanded/
    - lib/presentation/widgets/expandicon/
    - lib/presentation/widgets/dropdownbutton/
    - lib/presentation/widgets/expansionpanellist/
    - lib/presentation/widgets/expansionpanel/
    - lib/presentation/widgets/expansiontile/
    - lib/presentation/widgets/fadeinimage/
    - lib/presentation/widgets/fadetransition/
    - lib/presentation/widgets/filterchip/
    - lib/presentation/widgets/fittedbox/
    - lib/presentation/widgets/flexible/
    - lib/presentation/widgets/floatingactionbutton/
    - lib/presentation/widgets/flow/
    - lib/presentation/widgets/flutterlogo/
    - lib/presentation/widgets/form/
    - lib/presentation/widgets/fractionaltranslation/
    - lib/presentation/widgets/futurebuilder/
    - lib/presentation/widgets/fractionallysizedbox/
    - lib/presentation/widgets/gesturedetector/
    - lib/presentation/widgets/gridpaper/
    - lib/presentation/widgets/gridtile/
    - lib/presentation/widgets/gridtilebar/
    - lib/presentation/widgets/gridview/
    - lib/presentation/widgets/hero/
    - lib/presentation/widgets/icon/
    - lib/presentation/widgets/iconbutton/
    - lib/presentation/widgets/ignorepointer/
    - lib/presentation/widgets/image/
    - lib/presentation/widgets/indexedstack/
    - lib/presentation/widgets/inkwell/
    - lib/presentation/widgets/inputchip/
    - lib/presentation/widgets/interactiveviewer/
    - lib/presentation/widgets/layoutbuilder/
    - lib/presentation/widgets/limitedbox/
    - lib/presentation/widgets/linearprogressindicator/
    - lib/presentation/widgets/listener/
    - lib/presentation/widgets/listtile/
    - lib/presentation/widgets/listview/
    - lib/presentation/widgets/listwheelscrollview/
    - lib/presentation/widgets/longpressdraggable/
    - lib/presentation/widgets/materialapp/
    - lib/presentation/widgets/materialbanner/
    - lib/presentation/widgets/materialbutton/
    - lib/presentation/widgets/modalbarrier/
    - lib/presentation/widgets/mouseregion/
    - lib/presentation/widgets/navigationbar/
    - lib/presentation/widgets/notificationlistener/
    - lib/presentation/widgets/offstage/
    - lib/presentation/widgets/opacity/
    - lib/presentation/widgets/orientationbuilder/
    - lib/presentation/widgets/outlinedbutton/
    - lib/presentation/widgets/overflowbar/
    - lib/presentation/widgets/overflowbox/
    - lib/presentation/widgets/padding/
    - lib/presentation/widgets/pageview/
    - lib/presentation/widgets/physicalmodel/
    - lib/presentation/widgets/physicalshape/
    - lib/presentation/widgets/placeholder/
    - lib/presentation/widgets/platformmenubar/
    - lib/presentation/widgets/popupmenubutton/
    - lib/presentation/widgets/positioned/
    - lib/presentation/widgets/positionedtransition/
    - lib/presentation/widgets/preferredsize/
    - lib/presentation/widgets/radio/
    - lib/presentation/widgets/radiolisttile/
    - lib/presentation/widgets/rangeslider/
    - lib/presentation/widgets/rawautocomplete/
    - lib/presentation/widgets/rawchip/
    - lib/presentation/widgets/refreshindicator/
    - lib/presentation/widgets/reorderablelistview/
    - lib/presentation/widgets/richtext/
    - lib/presentation/widgets/rotatedbox/
    - lib/presentation/widgets/rotationtransition/
    - lib/presentation/widgets/row/
    - lib/presentation/widgets/safearea/
    - lib/presentation/widgets/scaffold/
    - lib/presentation/widgets/scaletransition/
    - lib/presentation/widgets/scrollbar/
    - lib/presentation/widgets/selectabletext/
    - lib/presentation/widgets/semantics/
    - lib/presentation/widgets/shadermask/
    - lib/presentation/widgets/shortcuts/
    - lib/presentation/widgets/simpledialog/
    - lib/presentation/widgets/singlechildscrollview/
    - lib/presentation/widgets/sizedbox/
    - lib/presentation/widgets/sizedoverflowbox/
    - lib/presentation/widgets/slidetransition/
    - lib/presentation/widgets/slider/
    - lib/presentation/widgets/sliverappbar/
    - lib/presentation/widgets/sliverfixedextentlist/
    - lib/presentation/widgets/slivergrid/
    - lib/presentation/widgets/sliverlist/
    - lib/presentation/widgets/sliveropacity/
    - lib/presentation/widgets/sliverpadding/
    - lib/presentation/widgets/slivertoboxadapter/
    - lib/presentation/widgets/snackbar/
    - lib/presentation/widgets/spacer/
    - lib/presentation/widgets/stack/
    - lib/presentation/widgets/stepper/
    - lib/presentation/widgets/streambuilder/
    - lib/presentation/widgets/switch/
    - lib/presentation/widgets/switchlisttile/
    - lib/presentation/widgets/systemmousecursors/
    - lib/presentation/widgets/tabbar/
    - lib/presentation/widgets/table/
    - lib/presentation/widgets/tabpageselector/
    - lib/presentation/widgets/text/
    - lib/presentation/widgets/textbutton/
    - lib/presentation/widgets/textfield/
    - lib/presentation/widgets/textformfield/
    - lib/presentation/widgets/textspan/
    - lib/presentation/widgets/themedata/
    - lib/presentation/widgets/timepicker/
    - lib/presentation/widgets/togglebuttons/
    - lib/presentation/widgets/tooltip/
    - lib/presentation/widgets/transform/
    - lib/presentation/widgets/tweenanimationbuilder/
    - lib/presentation/widgets/valuelistenablebuilder/
    - lib/presentation/widgets/verticaldivider/
    - lib/presentation/widgets/visibility/
    - lib/presentation/widgets/wrap/
