name: all_widgets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.0
  widget_with_codeview: ^3.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - lib/presentation/widgets/aboutdialog/
    - lib/presentation/widgets/aboutlisttile/
    - lib/presentation/widgets/absorbpointer/
    - lib/presentation/widgets/alertdialog/
    - lib/presentation/widgets/aling/
    - lib/presentation/widgets/animatedalign/
    - lib/presentation/widgets/animatedbuilder/
    - lib/presentation/widgets/animatedcontainer/
    - lib/presentation/widgets/animatedcrossfade/
    - lib/presentation/widgets/animateddefaulttextstyle/
    - lib/presentation/widgets/animatedicon/
    - lib/presentation/widgets/animatedlist/
    - lib/presentation/widgets/animatedmodalbarrier/
    - lib/presentation/widgets/animatedopacity/
    - lib/presentation/widgets/animatedpadding/
    - lib/presentation/widgets/animatedphysicalmodel/
    - lib/presentation/widgets/animatedpositioned/
    - lib/presentation/widgets/animatedrotation/
    - lib/presentation/widgets/animatedsize/
    - lib/presentation/widgets/animatedswitcher/
    - lib/presentation/widgets/appbar/ 
    - lib/presentation/widgets/aspectratio/ 
    - lib/presentation/widgets/autocomplete/ 
    - lib/presentation/widgets/backdropfilter/ 
    - lib/presentation/widgets/banner/ 
    - lib/presentation/widgets/baseline/ 
    - lib/presentation/widgets/blocksemantics/ 
    - lib/presentation/widgets/bottomnavigationbar/ 
    - lib/presentation/widgets/bottomsheet/ 
    - lib/presentation/widgets/builder/ 
    - lib/presentation/widgets/card/ 
    - lib/presentation/widgets/center/ 
    - lib/presentation/widgets/checkbox/ 
    - lib/presentation/widgets/checkboxlisttile/ 
    - lib/presentation/widgets/chip/ 
    - lib/presentation/widgets/choicechip/ 
    - lib/presentation/widgets/circleavatar/ 
    - lib/presentation/widgets/circularprogressindicator/ 
    - lib/presentation/widgets/clipoval/
    - lib/presentation/widgets/clippath/
    - lib/presentation/widgets/cliprect/
    - lib/presentation/widgets/cliprrect/
    - lib/presentation/widgets/closebutton/
    - lib/presentation/widgets/coloredbox/
    - lib/presentation/widgets/colorfiltered/